baseurl = "https://www.example.com/"
languageCode = "en-us"
title = "German Car Model"
author = "Yoshiharu Yamashita"
copyright = "&copy; 2016. All rights reserved."
canonifyurls = true
paginate = 10

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "German Car Model"
  brand = "German Car<br>Model"
  googleAnalytics = "Your Google Analytics tracking ID"
  disqus = "Your Disqus shortname"
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  dateFormat = "02 Jan 2006, 15:04"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Product"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "product"
    url = "/product/"
  [[menu.main]]
    name = "Category"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 3
    identifier = "category"
    url = "/category/"
  [[menu.main]]
    name = "Single Product"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 3
    identifier = "singleproduct"
    url = "/singleproduct/"
  # [[menu.main]]
  #   name = "About"
  #   pre = "<i class='fa fa-user fa-fw'></i>"
  #   weight = 2
  #   identifier = "about"
  #   url = "/about/"
  # [[menu.main]]
  #   name = "Contact"
  #   pre = "<i class='fa fa-phone fa-fw'></i>"
  #   weight = 3
  #   url = "/contact/"

[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.
  twitter = "*"
  facebook = "*"
  instagram = "*"
  github = "yoshiharuyamashita"
  stackoverflow = "*"
  linkedin = "*"
